### ISSUE TITLE
#include <Elog.h> not found

### ISSUE THREAD

**Issue by davidandreoletti** [x821938/elog#4]
**Problem**

Syslog.cpp include `#include <Elog.h>`. However, platformio does not find the header in "system" directories.

**Env**

```
PLATFORM: Espressif 32 (51.3.0-x-stable) > Seeed Studio XIAO ESP32S3
HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash
DEBUG: Current (esp-builtin) External (cmsis-dap, esp-bridge, esp-builtin, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 @ 3.0.7 
 - framework-arduinoespressif32-libs @ 5.1.0+sha.632e0c2a9f 
 - tool-esptoolpy @ 4.8.1 
 - tool-mklittlefs @ 3.2.0 
 - tool-riscv32-esp-elf-gdb @ 12.1.0+20221002 
 - tool-xtensa-esp-elf-gdb @ 12.1.0+20221002 
 - toolchain-riscv32-esp @ 12.2.0+20230208 
 - toolchain-xtensa-esp32s3 @ 12.2.0+20230208
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 51 compatible libraries
Scanning dependencies...
Dependency Graph
|-- Elog @ 2.0.5
|-- AdvancedLogger @ 1.3.0
|-- Adafruit TinyUSB Library @ 3.4.1
|-- ESP32-BLE-Gamepad @ 0.5.5
|-- NimBLE-Arduino @ 2.0.0+sha.7dc7194
|-- WiFi @ 3.0.7
Building in release mode
Compiling .pio/build/adapter_ble_generic/lib39c/Elog/Mix/mix.cpp.o
Compiling .pio/build/adapter_ble_generic/lib39c/Elog/Sd/Sd.cpp.o
Compiling .pio/build/adapter_ble_generic/lib39c/Elog/SimpleSerial/SimpleSerial.cpp.o
Compiling .pio/build/adapter_ble_generic/lib39c/Elog/Spiffs/spiffs.cpp.o
.pio/libdeps/adapter_ble_generic/Elog/src/Mix/mix.cpp:2:10: fatal error: Elog.h: No such file or directory

**************************************************************
* Looking for Elog.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Elog.h"
* Web  > https://registry.platformio.org/search?q=header:Elog.h
*
**************************************************************

    2 | #include <Elog.h>
      |          ^~~~~~~~
compilation terminated.
Compiling .pio/build/adapter_ble_generic/lib39c/Elog/Syslog/Syslog.cpp.o
*** [.pio/build/adapter_ble_generic/lib39c/Elog/Mix/mix.cpp.o] Error 1
.pio/libdeps/adapter_ble_generic/Elog/src/Sd/Sd.cpp:1:10: fatal error: Elog.h: No such file or directory
```

**Comment by Stefan300381** [comment]
Same here. Took me 2,5hours to find this issue being listed here. Tried everything and didn't get 2.0.5 to work. No issues to compile with 2.0.4

**Comment by davidandreoletti** [comment]
Hi @x821938,

Would you mind confirming the issue on your side too - please ?

**Comment by ChangYanChu** [comment]
Hi bro @davidandreoletti , I encountered the same issue and here's how I solved it:

In the `platformio.ini` configuration, make the following adjustments:

Original:
```
lib_deps = 
	x385832/Elog@^2.0.5
```

Adjusted:
```
lib_deps = 
	https://github.com/x821938/elog
```

Hope this helps you. Good luck!

**Comment by jack-changyan** [comment]
@davidandreoletti

**Comment by davidandreoletti** [comment]
@ChangYanChu Thanks!
