### ISSUE TITLE
SyslogExample doesn't compile

### ISSUE THREAD

**Issue by davo-downunder** [x821938/elog#8]
Nice library!

I must be doing something wrong but it doesn't compile in the Arduino IDE 2.3.6.  Any clues for me?

Without "ELOG_SYSLOG_ENABLE" defined, it fails with "no member named 'configureSyslog'

If it is defined, I get the rather weird error:
```
/home/davo/.arduino15/packages/esp32/tools/esp-x32/2507/bin/../lib/gcc/xtensa-esp-elf/14.2.0/../../../../xtensa-esp-elf/bin/ld: /home/davo/.cache/arduino/sketches/8B1E7C2285BB36EA900E75ED88454828/sketch/SyslogExample.ino.cpp.o:(.literal._Z5setupv+0x18): undefined reference to `_ZN4Elog15configureSyslogEPKctS1_bth'
/home/davo/.arduino15/packages/esp32/tools/esp-x32/2507/bin/../lib/gcc/xtensa-esp-elf/14.2.0/../../../../xtensa-esp-elf/bin/ld: /home/davo/.cache/arduino/sketches/8B1E7C2285BB36EA900E75ED88454828/sketch/SyslogExample.ino.cpp.o:(.literal._Z5setupv+0x1c): undefined reference to `_ZN4Elog14registerSyslogEhhhPKc'
/home/davo/.arduino15/packages/esp32/tools/esp-x32/2507/bin/../lib/gcc/xtensa-esp-elf/14.2.0/../../../../xtensa-esp-elf/bin/ld: /home/davo/.cache/arduino/sketches/8B1E7C2285BB36EA900E75ED88454828/sketch/SyslogExample.ino.cpp.o: in function `_Z5setupv':
/home/davo/src/Arduino/libraries/Elog/examples/SyslogExample/SyslogExample.ino:33:(.text._Z5setupv+0x44): undefined reference to `_ZN4Elog15configureSyslogEPKctS1_bth'
/home/davo/.arduino15/packages/esp32/tools/esp-x32/2507/bin/../lib/gcc/xtensa-esp-elf/14.2.0/../../../../xtensa-esp-elf/bin/ld: /home/davo/src/Arduino/libraries/Elog/examples/SyslogExample/SyslogExample.ino:36:(.text._Z5setupv+0x66): undefined reference to `_ZN4Elog14registerSyslogEhhhPKc'
collect2: error: ld returned 1 exit status
exit status 1

Compilation error: exit status 1
```

**Comment by x821938** [comment]
Should be fixed now
